doc.type.html
html lang en
script
header=document create.element(header)
header.style.backgroundcolor=#4caf50
header.style.color=’white’
header.style.padding=’10px’
header.style.textalign=’center’
header.style.text.fontsize=’24px’
header.textcontent=’welcome to covid strings2’
document appendchild(header)
<header.html>
heading variables 
the heading numbers that determine where each heading and subheading go 
heading1=keywords
heading2=online references 
heading3=covid strings keyword search engine
heading4=script templates
subheading1=script a
subheading2=script b
subheading3=script c
subheading4=script d
subheading5=script e
subheadin6=script f
subheading7=script g
subheading8=script h
subheading9=script i
subheading10=script j
subheading11=script k
subheading12=script l
subheading13=script m
subheading14=script n
subheading15=script o
subheading16=script p
subheading17=script q
subheading18=script r
subheading19=script s
filename=covid strings2 key words.js
let original string=”
let word to add-
let updated string {original string} {word to add}
console log updated string
<header.html>
keywords
key search words for covid strings2
covid strings2 key word list=[shorter than soda can on venus,rihana,super spreader,sun cubed,beer,pill,dexie,fifth harmonies,aaron rodgers worse than crime, astrazencia saturn,
vitamin d,medical doctors perscription,”one”+”and”+”four”+”twenty”+”firsts,46 to 43 percent,bubble round robin format,vitamin d exposure natural]
string manger non-concatenated
insert string(entity,string)
entity.element.text=string
string manager insert string
string=””
string manger concatenated
insert string(entity,string)
entity.element.text=string
string manager insert string
string=””
for string in covid strings key word list
select characters
edit diffuse property
desired color=green
<header.html>
online references 
links to articles that correspond to phrases in covid strings2
covid strings2 reference list=[a:post-lockdown anxiety:types and coping techniques (medicalnewstoday.com)b:venus fact sheet(nasa.gov),c:remote work is here to stay and will increase into2023,experts say (forbes.com),d:https://www.merriam-webster.com/words-at-play/super-spreader-figurative
e:2023 toyota gr supra review,pricing,and specs (caranddriver.com),f:https://www.nytimes.com/2020/10/07/us/politics/trump-coronavirus-blessing.html,g:https://www.cbsnews.com/news/no-coronas-beer-sales-did-not-suffer-from-the-coronavirus,h:https://www.businessinsider.com/elon-musk-tweets-take-the-red-pill-what-it-means-2020-5
i:dexamethasone uses,dosage & side effects -drugs.com,j:https://www.azlyrics.com/lyrics/fifthharmony/workfromhome.html,k:https://www.nbcsports.com/chicago/bears/did-aaron-rodgers-lie-about-his-covid-19-vaccination-status,l:https://www.consumerreports.org/cars/saturn/astra/2008/reliability/,m:how does vitamin d supplementation impact covid-19 vaccine efficacy? (news-medical.net) 
n:acura mdx |premium performance suv|acura.com,o:https://www.cnn.com/videos/media/2021/03/12/colbert-late-night-pandemic-anniversary-orig.cnn,p:polls show how frustrated americans are with covid restrictions -the new york times(nytimes.com)
q:https://www.espn.com/nba/story/_/id/30055011/everything-happened-nba-bubble,r:https://www.sportingnews.com/us/nhl/news/nhl-stanley-cup-playoff-bracket-format/Q81rq38mwrwlkelq1ukbqfg9], s:vitamin d3 and k2 and their potential contribution to reducing the covid-19 mortality rate-pmc(nih.gov)
<header.html>
covid strings keyword search engine
the search engine in covid strings 
game data=data in covid strings 
covid strings online reference list.transfer data  
html select covid strings online reference  list
get element By id submit button
selectelement=getelementbyid(question number) 
selectedoptions=(options a-d)
(selectelement,.selectedoptions).map(option>=optionvalue)
getElementbyid(output.textcontent) 
reference array=array of online references in covid strings key words file
search game data(query)
Lowercasequery=query to lowercase
return game data filter(item)
item.nametolowercase.includes(lowercasequery)
item.typetolowercase.includes(lowercasequery)
item.descriptiontolowercase.includes(lowercasequery)
uppercasequery=query to uppercase
return game data filter(item)
item.nametouppercase.includes(uppercasequery)
item.typetouppercase.includes(uppercasequery)
item.descriptiontouppercase.includes(uppercasequery)
<input type =”text” 
id=”search box”
<div id search results>
search box=document get element by id (search box)
search results=document get element by id (search results)
search box add event listener (input)
query=searchbox.value
results=search game data(query)
search results inner html=results.map(item)
div class result-item
<name item name>
<type item type>
item description 
<div>
join 
let debounce timer
searchbox add event listener(input)
cleartimeout(debouncetimer)
debouncetimer=set timeout
query=searchbox.value
results=search game data (query)
<header.html>
script templates
code for accessing the references
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
<subheading.html>
script a
the script for the website marked as website a in covid strings online reference list 
a=pc.create script(a);
a.attributes.add(foobar, {type:entity});
a.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
<subheading.html>
script b
the script for the website marked as website b in covid strings online reference list 
b=pc.create script(b);
b.attributes.add(foobar,{type:entity});
b.prototype.initialize=function() 
console.log(this.foobar.name);
asset this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
<subheading.html>
script c
the script for the website marked as website c in covid strings online reference list 
c=pc.createscript(c);
c.attributes.add(foobar,{type:entity});
c.prototype.initialize=function()
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
<subheading.html>
script d
the script for the website marked as website d in covid strings online reference list 
d=pc.create script(d);
d.attributes.add(foobar,{type:entity});
d.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
<subheading.html>
script e
the script for the website marked as website e in covid strings online reference list 
e=pc.create script(e);
e.attributes.add(foobar,{type:entity});
e.prototype.initialize=function() 
console.log(this.foobar.name);
asset= this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
<subheading.html>
script f
the script for the website marked as website e in covid strings online reference list 
f=pc.create script(f);
f.attributes.add(foobar,{type:entity});
f.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
<subheading.html>
script g
the script for the website marked as website e in covid strings online reference list 
g=pc.create script(g);
g.attributes.add(foobar,{type:entity});
g.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
<subheading.html>
script h
the script for the website marked as website h in covid strings online reference list 
h =pc.createscript(h);
h.attributes.add(foobar,{type:entity});
h.prototype.initialize =function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instanite
entity script foobar=this entity
entity reparnet (this.entity)
<subheading.html>
script i
the script for the website marked as website i in covid strings online reference list 
i=pc.create script(i);
i.attributes.add(foobar,{type:entity});
i.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
<subheading.html>
script j
the script for the website marked as website j in covid strings online reference list 
j=pc.createscript(j);
j.attributes.add(foobar, {type:entity});
j.prototype.initialize =function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
<subheading.html>
script k
the script for the website marked as website k in covid strings online reference list 
k=pc.createscript(k);
k.attributes.add(foobar,{type:entity});
k.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
<subheading.html>
script h
the script for the website marked as website h in covid strings online reference list 
l=pc.createscript(l);
l.attributes.add(foobar, {type:entity});
l.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
<subheading.html>
script m
The script for the website marked as website h in covid strings online reference list 
m=pc.create script(m);
m.attributes.add(foobar,{type:entity});
m.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
<subheading.html>
script n
the script for the website marked as website h in covid strings online reference list 
n=pc.create script(n);
n.attributes.add(foobar,{type:entity});
n.prototype.initialize =function() 
console.log(this.foobar.name);
asset= this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
<subheading.html>
script o
the script for the website marked as website h in covid strings online reference list 
o=pc.create script(o);
o.attributes.add(foobar,{type:entity});
o.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
<subheading.html>
script p
the script for the website marked as website p in covid strings online reference list 
p=pc.create script(p);
p.attributes.add(foobar, {type:entity});
p.prototype.initialize =function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
<subheading.html>
script q
the script for the website marked as website h in covid strings online reference list 
q=pc.create script(q);
q.attributes.add(foobar,{type:entity});
q.prototype.initialize =function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
<subheading.html>
script r
the script for the website marked as website h in covid strings online reference list 
r=pc.create script(r);
r.attributes.add(foobar,{type:entity});
r.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
<subheading.html>
script s
the script for the website marked as website s in covid strings online reference list 
s=pc.createscript(s);
s.attributes.add(foobar,{type:entity});
s.prototype.initialize =function() 
console.log(this.foobar.name);
return filename
